// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: shark.proto

package shark

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_UNKNOWN PacketType = 0
	PacketType_PRE     PacketType = 1
	PacketType_POST    PacketType = 2
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PRE",
		2: "POST",
	}
	PacketType_value = map[string]int32{
		"UNKNOWN": 0,
		"PRE":     1,
		"POST":    2,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_shark_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_shark_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_shark_proto_rawDescGZIP(), []int{0}
}

type GetPacketsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     string     `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	PacketType PacketType `protobuf:"varint,2,opt,name=PacketType,proto3,enum=PacketType" json:"PacketType,omitempty"`
}

func (x *GetPacketsInput) Reset() {
	*x = GetPacketsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shark_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPacketsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPacketsInput) ProtoMessage() {}

func (x *GetPacketsInput) ProtoReflect() protoreflect.Message {
	mi := &file_shark_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPacketsInput.ProtoReflect.Descriptor instead.
func (*GetPacketsInput) Descriptor() ([]byte, []int) {
	return file_shark_proto_rawDescGZIP(), []int{0}
}

func (x *GetPacketsInput) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *GetPacketsInput) GetPacketType() PacketType {
	if x != nil {
		return x.PacketType
	}
	return PacketType_UNKNOWN
}

type GetPacketsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload   []byte                 `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Time      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	SslKeyLog []byte                 `protobuf:"bytes,3,opt,name=SslKeyLog,proto3" json:"SslKeyLog,omitempty"`
}

func (x *GetPacketsOutput) Reset() {
	*x = GetPacketsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shark_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPacketsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPacketsOutput) ProtoMessage() {}

func (x *GetPacketsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_shark_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPacketsOutput.ProtoReflect.Descriptor instead.
func (*GetPacketsOutput) Descriptor() ([]byte, []int) {
	return file_shark_proto_rawDescGZIP(), []int{1}
}

func (x *GetPacketsOutput) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetPacketsOutput) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GetPacketsOutput) GetSslKeyLog() []byte {
	if x != nil {
		return x.SslKeyLog
	}
	return nil
}

var File_shark_proto protoreflect.FileDescriptor

var file_shark_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x0a, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x73, 0x6c, 0x4b, 0x65, 0x79, 0x4c, 0x6f,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x73, 0x6c, 0x4b, 0x65, 0x79, 0x4c,
	0x6f, 0x67, 0x2a, 0x2c, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x52, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02,
	0x32, 0x41, 0x0a, 0x08, 0x56, 0x70, 0x63, 0x73, 0x68, 0x61, 0x72, 0x6b, 0x12, 0x35, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x69, 0x64, 0x61, 0x6e, 0x73, 0x74, 0x65, 0x65, 0x6c, 0x65, 0x2f, 0x66, 0x6c,
	0x6f, 0x77, 0x64, 0x6f, 0x67, 0x2f, 0x67, 0x77, 0x6c, 0x62, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shark_proto_rawDescOnce sync.Once
	file_shark_proto_rawDescData = file_shark_proto_rawDesc
)

func file_shark_proto_rawDescGZIP() []byte {
	file_shark_proto_rawDescOnce.Do(func() {
		file_shark_proto_rawDescData = protoimpl.X.CompressGZIP(file_shark_proto_rawDescData)
	})
	return file_shark_proto_rawDescData
}

var file_shark_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shark_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shark_proto_goTypes = []interface{}{
	(PacketType)(0),               // 0: PacketType
	(*GetPacketsInput)(nil),       // 1: GetPacketsInput
	(*GetPacketsOutput)(nil),      // 2: GetPacketsOutput
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_shark_proto_depIdxs = []int32{
	0, // 0: GetPacketsInput.PacketType:type_name -> PacketType
	3, // 1: GetPacketsOutput.Time:type_name -> google.protobuf.Timestamp
	1, // 2: Vpcshark.GetPackets:input_type -> GetPacketsInput
	2, // 3: Vpcshark.GetPackets:output_type -> GetPacketsOutput
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shark_proto_init() }
func file_shark_proto_init() {
	if File_shark_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shark_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPacketsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shark_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPacketsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shark_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shark_proto_goTypes,
		DependencyIndexes: file_shark_proto_depIdxs,
		EnumInfos:         file_shark_proto_enumTypes,
		MessageInfos:      file_shark_proto_msgTypes,
	}.Build()
	File_shark_proto = out.File
	file_shark_proto_rawDesc = nil
	file_shark_proto_goTypes = nil
	file_shark_proto_depIdxs = nil
}
